services:
  nearby-places-recommendation-app:
    container_name: nearby-places-recommendation-app
    build: .
    image: ckdgus1010/nearby-places-recommendation-app
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "80:8080"
    restart: always